import { CharacterDef } from '../types';
import { BOSS_CHARACTERS } from './bossTypes';

export const CHARACTERS: CharacterDef[] = [
  {
    id: 'stickman',
    name: 'Stickman (Default)',
    userName: 'Fighter Stickman',
    standName: 'Stickman Spirit',
    title: 'Pure Martial Arts (No Special Skills)',
    bodyColor: '#e2e8f0',
    standColor: '#64748b',
    auraColor: 'grey',
    eyeColor: '#94a3b8',
    barrageCry: 'HA HA HA HA!',
    specialMove: 'Basic Strike',
    stats: {
      power: 'B',
      speed: 'B',
      range: 'C',
      durability: 'B',
    },
    skillsList: [
      { id: 'basic_punch', name: 'Straight Punch', command: 'J (Heavy)', description: 'Pukulan lurus dasar tanpa skill khusus.' },
      { id: 'basic_rush', name: 'Fist Rush', command: 'K (Barrage)', description: 'Rentetan pukulan tangan kosong cepat.' },
    ],
    description: 'Model karakter stickman default netral tanpa skill The World atau kemampuan khusus, mengandalkan pukulan dan pergerakan murni.',
  },
  {
    id: 'jotaro',
    name: 'Jotaro Kujo',
    userName: 'Jotaro Kujo',
    standName: 'Star Platinum',
    title: 'Precision, Unbreakable Spirit & Time Stop',
    bodyColor: '#cbd5e1',
    standColor: '#9333ea',
    auraColor: 'purple',
    eyeColor: '#facc15',
    barrageCry: 'ORA ORA ORA ORA!',
    specialMove: 'Star Platinum: The World',
    timeStopDurationSec: 5,
    stats: {
      power: 'S',
      speed: 'A+',
      range: 'C (High with Star Finger)',
      durability: 'A+',
    },
    skillsList: [
      { id: 'heavy_punch', name: 'Heavy Strike (Star Platinum)', command: 'J (Heavy)', description: 'Pukulan berat Stand Star Platinum dengan jangkauan dan knockback tinggi.' },
      { id: 'ora_barrage', name: 'ORA ORA Rush', command: 'K (Barrage)', description: 'Rentetan pukulan Stand super cepat beruntun berdaya hancur tinggi.' },
      { id: 'star_finger', name: 'Star Finger', command: 'U (Skill 1)', description: 'Horizontal strike berjangkauan panjang berkecepatan tinggi yang memicu stun singkat.' },
      { id: 'star_vacuum', name: 'Star Vapor (Inhale)', command: 'I (Skill 2)', description: 'Menghirup udara kencang, menyedot lawan mendekat, dan memicu status Guard Break.' },
      { id: 'stand_leap', name: 'Stand Leap', command: 'O (Skill 3)', description: 'Lompatan tinggi dibantu dorongan Stand untuk mobilitas di udara.' },
      { id: 'stand_parry', name: 'Star Guard Parry', command: 'P (Skill 4)', description: 'Stance menangkis otomatis, menetralkan serangan dan memicu counter strike.' },
      { id: 'ora_beatdown', name: 'ORA Beatdown (Heavy Combo)', command: 'L (Skill 5)', description: 'Rentetan ORA beruntun masif yang diakhiri hantaman pentalan kuat.' },
      { id: 'time_stop', name: 'Time Stop (The World)', command: 'T (Time Stop)', description: 'Menghentikan waktu selama 5 detik (Membutuhkan Energy 80%+).' },
    ],
    description: 'Petarung jarak dekat dengan mobilitas tinggi, counter parry, dan kemampuan menghentikan waktu secara instan.',
  },
  {
    id: 'dio',
    name: 'DIO Brando',
    userName: 'DIO Brando',
    standName: 'The World',
    title: 'Vampiric Might, Precision & Time Stop',
    bodyColor: '#fef08a',
    standColor: '#facc15',
    auraColor: 'gold',
    eyeColor: '#ef4444',
    barrageCry: 'MUDA MUDA MUDA MUDA!',
    specialMove: 'The World: Time Stop & Road Roller',
    timeStopDurationSec: 9,
    stats: {
      power: 'S+',
      speed: 'S',
      range: 'B',
      durability: 'S (Vampiric Heal)',
    },
    skillsList: [
      { id: 'dio_heavy', name: 'Heavy Kick / Strike', command: 'J (Heavy)', description: 'Tendangan atau pukulan berat The World yang memicu knockback.' },
      { id: 'muda_barrage', name: 'MUDA MUDA Rush', command: 'K (Barrage)', description: 'Rentetan pukulan beruntun super cepat dari Stand The World.' },
      { id: 'knife_throw', name: 'Checkmate (Knife Throw)', command: 'U (Skill 1)', description: 'Melemparkan 3 pisau pembunuh berkecepatan tinggi secara horizontal.' },
      { id: 'blood_drain', name: 'Vampiric Drain', command: 'I (Skill 2)', description: 'Mencengkeram lawan, menyedot darah untuk memulihkan HP dan memicu Stun.' },
      { id: 'street_sign', name: 'Street Sign Smash', command: 'O (Skill 3)', description: 'Menghantamkan papan tanda jalan raksasa ke darat berdamage tinggi.' },
      { id: 'space_ripper', name: 'Space Ripper Stingy Eyes', command: 'P (Skill 4)', description: 'Tembakan laser cairan murni dari mata berdaya tembus tinggi.' },
      { id: 'teleport', name: 'Time Blink (Teleport)', command: 'L (Skill 5)', description: 'Berteleportasi secara instan ke posisi belakang lawan.' },
      { id: 'time_stop_dio', name: 'The World: Time Stop', command: 'T (Time Stop)', description: 'Menghentikan waktu selama 9 detik untuk bebas menyerang.' },
      { id: 'road_roller', name: 'ROAD ROLLER DA!', command: 'Y (Ultimate)', description: 'Menjatuhkan Road Roller masif, menghantam beruntun dan memicu ledakan.' },
    ],
    description: 'Petarung dominan berjangkauan luas dengan pemulihan HP vampir, laser jarak jauh, teleportasi, dan ultimate Road Roller.',
  },
  {
    id: 'crazy_diamond',
    name: 'Josuke Higashikata',
    userName: 'Josuke Higashikata',
    standName: 'Crazy Diamond',
    title: 'Restoration, Enrage & Terrain Modification',
    bodyColor: '#e0e7ff',
    standColor: '#38bdf8',
    auraColor: 'cyan',
    eyeColor: '#0284c7',
    barrageCry: 'DORA RARA RARA RARA!',
    specialMove: 'Crazy Diamond: Rock Trapping & Hair Enrage',
    stats: {
      power: 'A+',
      speed: 'A',
      range: 'B',
      durability: 'S (Restoration)',
    },
    skillsList: [
      { id: 'josuke_heavy', name: 'Crazy Strike', command: 'J (Heavy)', description: 'Pukulan berat Crazy Diamond berjangkauan menengah.' },
      { id: 'dora_barrage', name: 'DORA RARA Rush', command: 'K (Barrage)', description: 'Rentetan pukulan beruntun cepat yang menghancurkan pertahanan lawan.' },
      { id: 'homing_shard', name: 'Restored Glass Shard', command: 'U (Skill 1)', description: 'Menembakkan pecahan kaca yang kembali otomatis menyerang lawan dari belakang.' },
      { id: 'rock_trap', name: 'Angelo Rock Wall', command: 'I (Skill 2)', description: 'Membentuk dinding batu dari tanah untuk memblokir serangan dan mengurung lawan.' },
      { id: 'dora_counter', name: 'Restoration Counter', command: 'O (Skill 3)', description: 'Stance menangkis yang mengembalikan damage serangan lawan.' },
      { id: 'hair_enrage', name: 'Hair Insult Enrage', command: 'P (Skill 4)', description: 'Josuke mengamuk ketika gaya rambutnya dihina! Meningkatkan speed & attack 50% selama 8s.' },
      { id: 'ground_shatter', name: 'Ground Fissure Punch', command: 'L (Skill 5)', description: 'Menghantam tanah, menciptakan ledakan pecahan batu area darat.' },
    ],
    description: 'Petarung serba bisa dengan jebakan dinding batu, pecahan kaca homing, dan buff mengamuk (Hair Enrage).',
  },
  {
    id: 'king_crimson',
    name: 'Diavolo',
    userName: 'Diavolo (Boss Passione)',
    standName: 'King Crimson',
    title: 'Time Erasure, Epitaph & Donut Execution',
    bodyColor: '#f43f5e',
    standColor: '#be123c',
    auraColor: 'crimson',
    eyeColor: '#fbbf24',
    barrageCry: 'KORE GA WAGA KING CRIMSON NO NORYOKU!',
    specialMove: 'Epitaph Prediction & Time Erase Donut',
    stats: {
      power: 'S+',
      speed: 'S+',
      range: 'C',
      durability: 'A (Time Erase)',
    },
    skillsList: [
      { id: 'kc_heavy', name: 'King Chop', command: 'J (Heavy)', description: 'Tebasan tangan mematikan King Crimson.' },
      { id: 'kc_barrage', name: 'Crimson Rush', command: 'K (Barrage)', description: 'Rentetan pukulan cepat bertenaga tinggi.' },
      { id: 'donut_strike', name: 'Donut Cleave (Flesh Strike)', command: 'U (Skill 1)', description: 'Tusukan mematikan menembus dada lawan berdamage sangat tinggi.' },
      { id: 'time_erase', name: 'Time Erasure (Kebal 2.5s)', command: 'I (Skill 2)', description: 'Menghapus waktu selama 2.5s. Kebal dari segala serangan dan bisa bergerak bebas.' },
      { id: 'epitaph_counter', name: 'Epitaph Prediction', command: 'O (Skill 3)', description: 'Melihat masa depan! Otomatis menghindari serangan dan muncul di belakang lawan.' },
      { id: 'time_erase_donut', name: 'Time Erase Donut Ambush', command: 'P (Skill 4)', description: 'Kombinasi hapus waktu dan serangan Donut mendadak dari belakang.' },
      { id: 'blood_blind', name: 'Blood Spray Blind', command: 'L (Skill 5)', description: 'Menyemprotkan darah ke mata lawan, memicu status pusing/blind.' },
    ],
    description: 'Petarung pembunuh mematikan dengan kemampuan menghapus waktu, memprediksi serangan lawan, dan eksekusi Donut Strike.',
  },
  {
    id: 'silver_chariot',
    name: 'Jean Pierre Polnareff',
    userName: 'J.P. Polnareff',
    standName: 'Silver Chariot',
    title: 'Fencing Mastery, Speed Armor & Sword Shoot',
    bodyColor: '#94a3b8',
    standColor: '#e2e8f0',
    auraColor: 'silver',
    eyeColor: '#38bdf8',
    barrageCry: 'HORA HORA HORA HORA!',
    specialMove: 'Armor Off Speed Burst & Ray Shooting',
    stats: {
      power: 'B',
      speed: 'S+ (Armor Off)',
      range: 'B',
      durability: 'B',
    },
    skillsList: [
      { id: 'fencing_stab', name: 'Rapier Thrust', command: 'J (Heavy)', description: 'Tusukan anggar presisi tinggi berkecepatan cepat.' },
      { id: 'chariot_barrage', name: 'HORA HORA Flurry', command: 'K (Barrage)', description: 'Rentetan tusukan pedang beruntun super cepat.' },
      { id: 'silver_blitz', name: 'Rapier Blitz Thrust', command: 'U (Skill 1)', description: 'Menerjang ke depan sambil menusukkan pedang berulang kali.' },
      { id: 'armor_off', name: 'Armor Off (Speed 2x)', command: 'I (Skill 2)', description: 'Melepas baju zirah Stand! Kecepatan gerak dan serangan meningkat 200%.' },
      { id: 'sword_shoot', name: 'Shooting Sword Ray', command: 'O (Skill 3)', description: 'Menembakkan mata pedang Chariot sebagai proyektil tajam jarak jauh.' },
      { id: 'afterimage_clone', name: 'Afterimage Clones', command: 'P (Skill 4)', description: 'Menciptakan bayangan ilusi cepat yang membingungkan arah serangan lawan.' },
      { id: 'million_thrust', name: 'Million Rapier Execution', command: 'L (Skill 5)', description: 'Kombinasi jutaan tusukan anggar berkecepatan tinggi.' },
    ],
    description: 'Petarung anggar cepat berkecepatan tinggi yang dapat melepas zirah Stand untuk menggandakan kecepatan serangan.',
  },
  {
    id: 'jonathan',
    name: 'Jonathan Joestar',
    userName: 'Jonathan Joestar',
    standName: 'Hamon Power (No Stand)',
    title: 'Hamon Master, Unyielding Courage & Sword of Pluck',
    bodyColor: '#3b82f6',
    standColor: '#f59e0b',
    auraColor: 'amber',
    eyeColor: '#60a5fa',
    barrageCry: 'SUNLIGHT YELLOW OVERDRIVE!',
    specialMove: 'Sunlight Yellow Overdrive & Sword of Luck/Pluck',
    stats: {
      power: 'A+',
      speed: 'B+',
      range: 'B',
      durability: 'S',
    },
    skillsList: [
      { id: 'jonathan_heavy', name: 'Hamon Heavy Punch', command: 'J (Heavy)', description: 'Pukulan bertenaga Hamon Emas.' },
      { id: 'jonathan_rush', name: 'Overdrive Rush', command: 'K (Barrage)', description: 'Rentetan pukulan tangan kosong bergelombang energi Hamon.' },
      { id: 'zoom_punch', name: 'Zoom Punch', command: 'U (Skill 1)', description: 'Memanjangkan engsel lengan untuk pukulan jangkauan jauh.' },
      { id: 'sendo_overdrive', name: 'Sendo Overdrive Wave', command: 'I (Skill 2)', description: 'Menyalurkan gelombang Hamon merambat di lantai/tanah.' },
      { id: 'scarlet_overdrive', name: 'Scarlet Overdrive (Fire)', command: 'O (Skill 3)', description: 'Pukulan Hamon bernyala api berdamage luka bakar.' },
      { id: 'pluck_sword', name: 'Sword of Pluck Slash', command: 'P (Skill 4)', description: 'Tebasan pedang keberanian Luck & Pluck bertenaga tinggi.' },
      { id: 'sunlight_yellow', name: 'Sunlight Yellow Overdrive!', command: 'L (Skill 5)', description: 'Puncak jurus Hamon bergelombang emas yang menghancurkan lawan.' },
    ],
    description: 'Pengguna Hamon sejati tanpa Stand dengan ketahanan fisik luar biasa, tebasan Pedang Pluck, dan Sunlight Yellow Overdrive.',
  },
  {
    id: 'joseph_young',
    name: 'Joseph Joestar (Young)',
    userName: 'Joseph (Young)',
    standName: 'Hamon & Trickery (No Stand)',
    title: 'Master Trickster, Clacker Volley & Tommy Gun',
    bodyColor: '#10b981',
    standColor: '#f59e0b',
    auraColor: 'emerald',
    eyeColor: '#34d399',
    barrageCry: 'RE-RE-RE-RE-RE-RE!!',
    specialMove: 'Next You Will Say & Clacker Volley Trap',
    stats: {
      power: 'B',
      speed: 'A',
      range: 'A',
      durability: 'B+',
    },
    skillsList: [
      { id: 'young_heavy', name: 'Trick Strike', command: 'J (Heavy)', description: 'Pukulan trik kejutan Joseph.' },
      { id: 'young_rush', name: 'Hamon Fist Barrage', command: 'K (Barrage)', description: 'Rentetan pukulan Hamon licik.' },
      { id: 'clacker_volley', name: 'Clacker Volley Boomerang', command: 'U (Skill 1)', description: 'Melemparkan bola Clacker berinfusi Hamon yang memantul kembali.' },
      { id: 'next_line', name: 'Next You Will Say! (Counter)', command: 'I (Skill 2)', description: 'Menebak kalimat lawan! Memicu stun lawan dan mengabaikan damage.' },
      { id: 'grenade_trick', name: 'Grenade Trap String', command: 'O (Skill 3)', description: 'Memasang perangkap granat tersembunyi di tanah.' },
      { id: 'tommy_gun', name: 'Tommy Gun Spray', command: 'P (Skill 4)', description: 'Menembakkan senapan Tommy Gun secara serentak ke depan.' },
      { id: 'nigerundayo', name: 'NIGERUNDAYO! (Tactical Escape)', command: 'L (Skill 5)', description: 'Lari taktis membelakangi lawan untuk memulihkan energy dan memberi jarak.' },
    ],
    description: 'Petarung trik licik dengan tebakan kalimat counter, lemparan Clacker Volley, perangkap granat, dan senapan Tommy Gun.',
  },
  {
    id: 'joseph_old',
    name: 'Joseph Joestar (Old)',
    userName: 'Joseph (Old)',
    standName: 'Hermit Purple',
    title: 'Hermit Purple Vines, Divination & Hamon Conductor',
    bodyColor: '#d97706',
    standColor: '#84cc16',
    auraColor: 'lime',
    eyeColor: '#f59e0b',
    barrageCry: 'OH MY GOD!! SAN OF A BITCH!!',
    specialMove: 'Hermit Purple Vine Grapple & Spirit Photo Divination',
    stats: {
      power: 'C',
      speed: 'C',
      range: 'S',
      durability: 'B',
    },
    skillsList: [
      { id: 'old_heavy', name: 'Vine Whip Strike', command: 'J (Heavy)', description: 'Sabetan sulur Hermit Purple.' },
      { id: 'old_rush', name: 'Hermit Vine Barrage', command: 'K (Barrage)', description: 'Rentetan sabetan sulur hijau berinfusi Hamon.' },
      { id: 'vine_grab', name: 'Hermit Vine Grapple', command: 'U (Skill 1)', description: 'Menarik lawan dari jarak jauh menggunakan sulur Hermit Purple.' },
      { id: 'overdrive_shock', name: 'Hamon Overdrive Shock', command: 'I (Skill 2)', description: 'Menyalurkan tersetrum listrik Hamon melalui sulur.' },
      { id: 'spirit_photo', name: 'Spirit Photo Divination', command: 'O (Skill 3)', description: 'Mendeteksi posisi lawan dan membuka pertahanannya.' },
      { id: 'oh_my_god', name: 'OH MY GOD!! (Taunt Buff)', command: 'P (Skill 4)', description: 'Teriakan khas Joseph! Mengagetkan lawan dan memulihkan energy.' },
      { id: 'vine_wrap_trap', name: 'Hermit Bind Execution', command: 'L (Skill 5)', description: 'Menglilit seluruh tubuh lawan dengan sulur berinfusi Hamon.' },
    ],
    description: 'Petarung jarak jauh mengandalkan sulur Hermit Purple untuk menarik, mengikat, dan menyetrum lawan dari jauh.',
  },
  {
    id: 'tooru',
    name: 'Tooru & Wonder of U',
    userName: 'Tooru (Wonder of U)',
    standName: 'Wonder of U',
    title: 'Calamity Flow, Head Doctor & Logic of the World',
    bodyColor: '#334155',
    standColor: '#0f172a',
    auraColor: 'calamity',
    eyeColor: '#e11d48',
    barrageCry: 'DO DO DO DE DA DA DA!',
    specialMove: 'Logic of Calamity & Extinction Meteor',
    stats: {
      power: 'EX',
      speed: 'C',
      range: '∞ (Universal)',
      durability: 'EX (Calamity Shield)',
    },
    skillsList: [
      { id: 'chill_tap', name: 'Chill Step (No Basic Punch)', command: 'J (Action)', description: 'Tooru berjalan santai sambil mendengarkan earphone, memicu kutukan Calamity pasif.' },
      { id: 'calamity_curse', name: 'Flow of Calamity (WoU Stalk)', command: 'K (Calamity Aura)', description: 'Wonder of U menatap lawan, mempercepat aktivasi kutukan nasib buruk.' },
      { id: 'head_doctor', name: 'Head Doctor Disguise', command: 'U (Skill 1)', description: 'Menyamar sebagai Satoru Akefu & berjalan membelakangi lawan. Kebal total (Invincible) selama 3 detik!' },
      { id: 'rock_insects', name: 'Rock Insects (Dododo De Dadada)', command: 'I (Skill 2)', description: 'Memanggil serangga batu pemangsa merayap di lantai yang memperlambat (slow) dan meracuni musuh.' },
      { id: 'traffic_hazard', name: 'Calamity Counter (Traffic Hazard)', command: 'O (Skill 3)', description: 'Stance kebal/counter. Setiap kali musuh mencoba menyerang, mobil nyasar langsung menabrak penyerang!' },
      { id: 'passive_info', name: 'Passive: Logic of Calamity', command: 'Passive (Always On)', description: 'Musuh yang mengejar atau menyerang Tooru akan terkena 1 dari 7 kutukan Calamity secara acak (Petir, Puing, Tersandung, Tabrakan Mobil, Terbakar, Sayatan Tajam, Ricochet). Lemah terhadap Time Stop!' },
      { id: 'meteor_extinction', name: 'Rain of Calamity & Meteor', command: 'Y / L (Ultimate)', description: 'Hujan badai Calamity menusuk lawan terus-menerus, diakhiri hantaman Meteor raksasa berledakan dahsyat!' },
    ],
    description: 'Petarung kutukan pamungkas Part 8 yang santai mendengarkan musik selagi Stand Wonder of U berjalan mandiri. Musuh yang mengejarnya dihantam nasib sial Calamity, namun tak berkutik saat Time Stop aktif.',
  },
  {
    id: 'pucci',
    name: 'Enrico Pucci',
    userName: 'Father Pucci',
    standName: 'Whitesnake',
    title: 'Gravity, Evolution & The Maiden of Heaven (Part 6)',
    bodyColor: '#1e1b4b',
    standColor: '#e2e8f0',
    auraColor: 'heaven',
    eyeColor: '#a855f7',
    barrageCry: 'HALELLUJAH! / MA-DE IN HEAVEN!',
    specialMove: '14 Words of Heaven -> C-Moon -> Universe Reset',
    stats: {
      power: 'EX',
      speed: 'EX (Infinite Acceleration)',
      range: '∞ (Universal Reset)',
      durability: 'A+',
    },
    skillsList: [
      { id: 'whitesnake_punch', name: 'Pistol Gunshot', command: 'J (Basic / Punch)', description: 'Pucci / Whitesnake menembakkan pistol dengan peluru tajam berkecepatan tinggi ke arah musuh (Stand aktif: Whitesnake yang memegang & menembakkan pistol).' },
      { id: 'whitesnake_rush', name: 'Whitesnake Barrage', command: 'K (Barrage)', description: 'Rentetan sabetan Stand Whitesnake cepat dengan peluang mencuri DISC lawan.' },
      { id: 'pucci_pistol', name: 'Pistol Shot', command: 'U (Skill 1)', description: 'Pucci mengeluarkan pistol dan menembakkan peluru cepat berkecepatan tinggi ke arah musuh.' },
      { id: 'memory_disc_extract', name: 'Memory DISC Extract', command: 'I (Skill 2)', description: 'Menyerang dan mencuri memori jurus lawan, memaksa seluruh skill musuh masuk mode cooldown instan.' },
      { id: 'acid_melt', name: 'Acid Melt Illusion', command: 'O (Skill 3)', description: 'Mengeluarkan cairan asam melumer di lantai yang memberikan efek slow berat dan damage over time.' },
      { id: 'stand_disc_command', name: 'Stand DISC Command', command: 'P (Skill 4)', description: 'Menembakkan DISC perintah ke tubuh lawan, membuat musuh membeku (Freeze) selama 1.5 detik.' },
      { id: '14_words_chant', name: '14 Words Recitation (Evolve)', command: 'L / Y (Evolve)', description: 'Membaca 14 kata rahasia selama 4.5 detik. Jika tidak terinterupsi serangan musuh, Pucci berevolusi menjadi C-MOON!' },
    ],
    description: 'Imam yang mengejar Surga ciptaan DIO. Memiliki sistem evolusi 3-Form (Whitesnake -> C-Moon -> Made in Heaven) dengan penimpaan skill set total, pergeseran gravitasi dinamis arena, dan akselerasi kecepatan tak terbatas.',
  },
  {
    id: 'gappy',
    name: 'Josuke Higashikata (Gappy)',
    userName: 'Josuke (Gappy)',
    standName: 'Soft & Wet',
    title: 'Utility Fighter & Absolute Defense Piercer (Part 8 JoJolion)',
    bodyColor: '#0284c7',
    standColor: '#38bdf8',
    auraColor: 'cyan',
    eyeColor: '#38bdf8',
    barrageCry: 'ORA ORA ORA ORA ORA ORA!!',
    specialMove: 'Plunder Bubble & Soft & Wet: Go Beyond',
    stats: {
      power: 'A',
      speed: 'A',
      range: 'S (Spinning Line)',
      durability: 'A',
    },
    skillsList: [
      { id: 'gappy_bubble_plunder', name: 'Bubble Plunder (Friction Strip)', command: 'U (Skill 1)', description: 'Melempar gelembung Plunder ke lantai yang mencuri gesekan tanah (musuh terpeleset & licin tanpa kendali).' },
      { id: 'gappy_shave_moisture', name: 'Shave & Moisture Theft', command: 'I (Skill 2)', description: 'Tembakan gelembung pencuri yang mengurangi Attack musuh 50% selama 6 detik dan memberikan Lifesteal +45 HP.' },
      { id: 'gappy_bubble_barrage', name: 'Bubble Shot Barrage', command: 'O (Skill 3)', description: 'Rentetan ORA ORA yang mengeluarkan ledakan puluhan gelembung sabun ber-damage tinggi.' },
      { id: 'gappy_bubble_trap', name: 'Bubble Shield & Trap', command: 'P (Skill 4)', description: 'Menciptakan Bubble Shield pelindung (Self) atau mengurung musuh dalam gelembung terapung (Stun 3 detik).' },
      { id: 'gappy_go_beyond', name: 'Soft & Wet: Go Beyond', command: 'Y / L (Ultimate)', description: 'Menembakkan garis berputar tak kasat mata dari tanda lahirnya! Serangan True Damage mutlak yang MENUSUK SEMUA LOGIKA ARENA (Mengabaikan Invulnerability, Time Stop, Calamity, & Defense).' },
      { id: 'gappy_passive', name: 'Passive: Plunder Bubble', command: 'Passive (Always On)', description: 'Setiap light attack (25% peluang) mencuri atribut musuh selama 2 detik: Friction Theft (musuh terpeleset), Sight Theft (layar gelap total), atau Sound Theft (SFX senyap).' },
    ],
    description: 'Utility Fighter bertopi pelaut dengan gelembung Soft & Wet yang mencuri properti fisik musuh. Serangan ultimate Go Beyond miliknya adalah garis tak kasat mata yang menembus semua logika arena dan pertahanan.',
  },
  {
    id: 'funny_valentine',
    name: 'Funny Valentine',
    userName: 'Funny Valentine',
    standName: 'Dirty Deeds Done Dirt Cheap (D4C)',
    title: 'Dual-Dimension Shift & Paradox Specialist (Part 7: Steel Ball Run)',
    bodyColor: '#f472b6',
    standColor: '#38bdf8',
    auraColor: 'dimensional',
    eyeColor: '#38bdf8',
    barrageCry: 'DOJYAA~~N! / D4C!',
    specialMove: 'D4C: Change to Parallel, Paradox Pull & Love Train',
    stats: {
      power: 'A',
      speed: 'A',
      range: '∞ (Multi-Dimensional)',
      durability: 'A (Conditional Dimension Swap)',
    },
    skillsList: [
      { id: 'valentine_basic_shot', name: 'Presidential Revolver & D4C Strike', command: 'J / Punch', description: 'Stand Off: Menembak 1 peluru revolver kepresidenan (45 Dmg). Stand On: Valentine menembak 1 peluru dan Stand D4C otomatis melompat maju memukul combo 2 kali!' },
      { id: 'valentine_parallel', name: 'Change to Parallel (Paradox Pull)', command: 'U (Skill 1)', description: 'Menjepit diri dengan bendera & pindah ke Dunia Paralel (kebal di Dunia Asli, melawan Active CPU Clone). Tekan ulang saat di Dunia Paralel untuk menarik CPU Clone ke Dunia Asli memicu Paradox Collision (Massive True Damage)!' },
      { id: 'valentine_clone_army', name: 'Parallel Self Army', command: 'I (Skill 2)', description: 'Memanggil 2 clone Valentine dari dimensi sejajar ke arena selama 4.5 detik. Berfungsi sebagai penyerang aktif dan nyawa cadangan (Life Insurance).' },
      { id: 'valentine_barrage', name: 'D4C Heavy Barrage', command: 'O (Skill 3)', description: 'D4C muncul melancarkan pukulan beruntun super cepat dan diakhiri dengan lemparan bendera yang memicu knockback + stun 1 detik.' },
      { id: 'valentine_love_train', name: 'D4C: Love Train', command: 'Y / P (Ultimate)', description: 'Mengaktifkan dinding cahaya pelindung vertikal keemasan selama 5.5 detik. 100% kebal dari semua damage/debuff & memantulkan serangan musuh menjadi true damage otomatis!' },
      { id: 'valentine_life_insurance', name: 'Passive: Life Insurance (Conditional Dimension Swap)', command: 'Passive (Conditional)', description: 'Jika HP Valentine menyentuh 0 saat ADA CLONE di arena, Valentine melempar bendera ke clone terdekat, mengambil alih tubuhnya, dan bangkit kembali dengan 35% HP! (Jika tidak ada clone, pasif mati & Valentine gugur).' },
    ],
    description: 'Presiden Amerika Serikat ke-23 yang bertarung dengan tembakan pistol revolver kepresidenan dan Stand D4C antar dimensi. Mampu berpindah ke Dunia Paralel, memicu ledakan tabrakan paradoks dimensional (Paradox Collision 650 True Damage), mengerahkan pasukan klon diri sejajar sebagai nyawa cadangan (Life Insurance), dan berlindung di balik dinding suci Love Train.',
  },
  {
    id: 'dipez',
    name: 'Dipez',
    userName: 'Dipez',
    standName: 'Glowing Man',
    title: 'Photon Atom Converter & Pure Light Man (Stand: Glowing Man)',
    bodyColor: '#e2e8f0',
    standColor: '#fef08a',
    auraColor: 'gold',
    eyeColor: '#fef08a',
    barrageCry: 'WHOAAAA!!!',
    specialMove: 'Star Maker / Pure Light Form',
    stats: {
      power: 'A',
      speed: 'S (∞ Evolved)',
      range: 'A',
      durability: 'B (100% Invincible Evolved)',
    },
    skillsList: [
      { id: 'dipez_photon_bullet', name: 'Photon Bullet / Photon Invisibility', command: 'U (Skill 1)', description: 'Base: Photon Bullet (Armor Piercing). Evolved: Photon Invisibility (Menjadi tak terlihat oleh musuh selama 6 detik).' },
      { id: 'dipez_flashbang', name: 'Flashbang / Omnipresent Map Laser', command: 'I (Skill 2)', description: 'Base: Flashbang (1.5s Blind). Evolved: Omnipresent Map Laser (Laser cahaya raksasa ke seluruh area map dengan damage besar & terbakar).' },
      { id: 'dipez_laser_cannon', name: 'Arm Laser / Speed of Light Blitz', command: 'O (Skill 3)', description: 'Base: Arm Laser Cannon (1.5s Laser + 5s Arm Lost). Evolved: Speed of Light Blitz (Melesat secepat cahaya ke seluruh titik arena, menghantam & membakar musuh).' },
      { id: 'dipez_evolution', name: 'Evolution Gamble (Glowing Man)', command: 'P (Skill 4)', description: 'RNG 50% Chance evolusi Manusia Cahaya Murni. Evolved: Star Maker (Burst Damage Raksasa & Super White Arena Burn 3s).' },
    ],
    description: 'Petarung foton yang bertarung mengonversi atom tubuh menjadi cahaya bersama Stand-nya, Glowing Man. Memiliki potensi evolusi RNG 50% menjadi Manusia Cahaya Murni (Invisibility, Map Laser, Speed of Light Blitz, & High Damage Star Maker).',
  },
  {
    id: 'arabian_fat',
    name: 'Arabian Fat',
    userName: 'Arabia Fats',
    standName: 'The Sun',
    title: 'The Sun & Desert Illusion (Part 3: Stardust Crusaders)',
    bodyColor: '#d97706',
    standColor: '#f59e0b',
    auraColor: 'amber',
    eyeColor: '#ef4444',
    barrageCry: 'KIKIKIKI! YAKETSUKERO!',
    specialMove: 'The Sun: Auto-Targeting Heat Lasers & Supernova',
    stats: {
      power: 'A',
      speed: 'E (Static Camouflage / A In Sky)',
      range: 'A (Entire Sky Arena)',
      durability: 'A (Mirror Fortress / E Exposed)',
    },
    skillsList: [
      { id: 'sun_laser', name: 'Focused Heat Ray Snipe', command: 'U (Skill 1)', description: 'Menembakkan berkas sinar laser panas terfokus dari The Sun ke koordinat tepat posisi musuh.' },
      { id: 'sun_mirage', name: 'Desert Mirage Illusion', command: 'I (Skill 2)', description: 'Menciptakan fatamorgana gurun pasir yang membingungkan musuh (membalikkan kontrol & mengacaukan penglihatan).' },
      { id: 'sun_bombardment', name: 'Prominence Solar Bombardment', command: 'O (Skill 3)', description: 'The Sun menghujani arena dengan 5 bola api proyektil solar flare berdaya ledak tinggi.' },
      { id: 'sun_supernova', name: 'Supernova Heatwave (Temperature Spike)', command: 'P / Y (Ultimate)', description: 'Menaikkan suhu arena seketika (+35°C), memicu ledakan gelombang panas global ke seluruh arena yang membakar musuh.' },
      { id: 'sun_mirror_passive', name: 'Passive: Mirror Camouflage & Heat Gauge', command: 'Passive', description: 'Arabian Fat bersembunyi di balik cermin ilusi (kebal & diam). The Sun di angkasa memicu kenaikan suhu arena (0-100°C) yang memperlambat musuh & membakarnya. Auto-Targeting Lasers menembak lebih cepat saat musuh bergerak/dash! Jika cermin hancur, nyawa Arabia Fat tersisa 1000 HP dan Stand The Sun tetap menyala di langit!' },
    ],
    description: 'Pengguna Stand The Sun berpenampilan jubah gurun dan serban yang bersembunyi di balik cermin kamuflase fatamorgana. Selama bersembunyi, ia tidak dapat bergerak dan mengandalkan The Sun di angkasa yang menaikkan temperatur suhu ruangan, menembakkan laser otomatis dengan frekuensi meningkat tajam jika musuh bergerak, hingga cermin kamuflasenya berhasil ditemukan dan dihancurkan oleh musuh.',
  },
  {
    id: 'michael',
    name: 'Michael Junister',
    userName: 'Michael Junister',
    standName: 'Hat Price',
    title: 'Ghost: Hat Price & Momentum Kinetic Arts',
    bodyColor: '#fed7aa',
    standColor: '#facc15',
    auraColor: 'gold',
    eyeColor: '#facc15',
    barrageCry: 'WRAAA!! WRAA WRAA WRAA!! WRAAAA!!',
    specialMove: 'Hat Price: Maximum Price (Supersonic Golden Blitz)',
    stats: {
      power: 'A+',
      speed: 'S',
      range: 'C (Close-Quarters Kinetic Combat)',
      durability: 'A',
    },
    skillsList: [
      { id: 'michael_palm_thrust', name: 'Golden Palm Thrust (Kinetic Surge)', command: 'U (Skill 1)', description: 'Menerjang maju dengan momentum tersimpan, menghantamkan telapak tangan emas yang menembus guard lawan dan memicu ledakan kinetik kompresi.' },
      { id: 'michael_counter', name: 'Flash Step Counter (Momentum Redirection)', command: 'I (Skill 2)', description: 'Stance counter bela diri; menyerap momentum serangan musuh lalu melesat dalam sekejap ke belakang lawan dan mendaratkan tendangan memutar berbalut aura emas yang menghempaskan musuh.' },
      { id: 'michael_axe_kick', name: 'Golden Axe Kick (Aura Impact Slam)', command: 'O (Skill 3)', description: 'Melompat tinggi dan menghantamkan tumit kaki berbalut energi kinetik tebal ke tanah, memicu gempa gelombang kejut yang melempar musuh ke udara.' },
      { id: 'michael_overdrive', name: 'Hat Price Overdrive (Golden Limbs Surge)', command: 'P (Skill 4)', description: 'Membakar simpanan Kinetic Meter secara intensif selama 6 detik: kecepatan melesat hipersonik, pukulan & tendangan melontarkan gelombang kejut emas berjarak jauh, dan damage meningkat.' },
      { id: 'michael_barrage', name: 'Kinetic Rush: Gold Gale (Hundred Slaps & Kicks)', command: 'L (Skill 5)', description: 'Kombinasi pukulan telapak dan tendangan beruntun ultra-cepat dengan teriakan "WRAAA!!", diakhiri dorongan telapak tangan ganda berdaya tolak masif.' },
      { id: 'michael_ultimate', name: 'HAT PRICE: MAXIMUM PRICE (Ultimate)', command: 'Y (Ultimate)', description: 'Puncak manifestasi momentum Hat Price! Michael melepaskan seluruh momentum kinetik yang tersimpan, melesat dalam pusaran kilat emas hipersonik menghujani musuh dari segala sudut.' },
    ],
    description: 'Pemuda 19 tahun berdarah Inggris-Irlandia dengan tampang rupawan, karisma tinggi, dan selendang sutra yang berkibar. Memegang nomor punggung 1 di balapan Devil\'s Competitive dengan kuda bernama George. Bersikap sombong, licik, kalkulatif, dan sinis. Ghost-nya "Hat Price" mampu menyerap dan menyimpan momentum kinetik benda, gerakan, dan benturan ke dalam Kinetic Meter, lalu melepaskannya untuk melipatgandakan akselerasi tubuh dan daya hantam serangannya.',
  },
  {
    id: 'perstein',
    name: 'Perstein',
    userName: 'Wally Wable (Perstein)',
    standName: 'Wable the Metal Cutter',
    title: 'Silence After The Storm (70m Drive Chains & Absolute Deflection)',
    bodyColor: '#334155',
    standColor: '#94a3b8',
    auraColor: 'metal',
    eyeColor: '#38bdf8',
    barrageCry: '...Shh... (70m Chain Whirl) ...Silence...',
    specialMove: 'Silence After The Storm: 70m Drive Chain Vortex Guillotine',
    stats: {
      power: 'A',
      speed: 'A+',
      range: 'A (70m Chain Reach)',
      durability: 'S (Awaken 2 Deflection)',
    },
    skillsList: [
      { id: 'perstein_chain_whip', name: '70m Drive Chain Snare', command: 'U (Skill 1)', description: 'Melontarkan rantai motor baja berkecepatan tinggi sejauh 70m, mencambuk dan menarik musuh mendekat ke arah Perstein.' },
      { id: 'perstein_chain_bind_shred', name: 'High-RPM Drive Chain Shred', command: 'I (Skill 2)', description: 'Melilit tubuh musuh dengan rantai motor berkecepatan RPM ekstrem, mengikis HP lawan dengan cabikan beruntun dan efek pendarahan/bleed.' },
      { id: 'perstein_spark_ignition', name: 'Metal Friction Spark Blast', command: 'O (Skill 3)', description: 'Menggesekkan rantai baja berkecepatan tinggi ke tanah dan musuh, memantik ledakan api percikan logam super panas yang membakar musuh.' },
      { id: 'perstein_awaken_deflection', name: 'Awaken 2: Absolute Chain Deflection', command: 'P (Skill 4)', description: 'Rantai motor tak kasat mata (invisible drive chain) yang otomatis melesat keluar menepis dan memantulkan segala serangan fisik & proyektil lawan saat mendekat.' },
      { id: 'perstein_awaken_touch', name: 'Awaken 1: Direct Touch Flesh Tear', command: 'L (Skill 5)', description: 'Dash menerjang menyentuh lawan, menumbuhkan rantai motor langsung di dalam tubuh musuh yang berputar dengan kecepatan hipersonik merobek daging lawan dengan True Damage.' },
      { id: 'perstein_ultimate', name: 'SILENCE AFTER THE STORM (Snare, Spin & Crush)', command: 'Y (Ultimate)', description: 'Melontarkan rantai motor 70m mengikat musuh, menariknya mendekat, memutar lilitan rantai berkecepatan RPM ekstrem, lalu meremas/mengikis habis musuh hingga mencapai keheningan total.' },
    ],
    description: 'Pria berusia 27 tahun dari Vancouver, Kanada. Berpenampilan sangat rapi, bertutur kata lembut, selalu tersenyum kecil, dan dikenal sangat sabar serta suka membantu di lingkungan sosialnya. Namun di balik sikap teladannya, ia menganggap segala kebisingan dan gangguan sebagai ancaman terhadap kedamaiannya, membasmi para pengganggu tanpa emosi demi menikmati keheningan total. Ghost-nya "Wable the Metal Cutter" berwujud humanoid metalik yang mampu mengeluarkan dan mengendalikan rantai motor/drive chain hingga panjang 70 meter dengan kecepatan putar ekstrem yang mencabik daging dan menangkis segala serangan secara otomatis.',
  },
];

export const PUCCI_FORM_SKILLS: Record<string, { standName: string; title: string; skillsList: Array<{ id: string; name: string; command: string; description: string }> }> = {
  whitesnake: {
    standName: 'Whitesnake',
    title: 'DISC Manipulation & 14 Words of Heaven',
    skillsList: [
      { id: 'pucci_pistol', name: 'Pistol Shot', command: 'U (Skill 1)', description: 'Pucci mengeluarkan pistol dan menembakkan peluru cepat berkecepatan tinggi ke arah musuh.' },
      { id: 'memory_disc_extract', name: 'Memory DISC Extract', command: 'I (Skill 2)', description: 'Menyerang dan mencuri memori jurus lawan, memaksa seluruh skill musuh masuk cooldown instan.' },
      { id: 'acid_melt', name: 'Acid Melt Illusion', command: 'O (Skill 3)', description: 'Mengeluarkan cairan asam melumer di lantai yang memberikan slow dan DoT.' },
      { id: 'stand_disc_command', name: 'Stand DISC Command', command: 'P (Skill 4)', description: 'Menembakkan DISC perintah untuk membekukan (Freeze) musuh selama 1.5 detik.' },
      { id: '14_words_chant', name: '14 Words Recitation (Evolve)', command: 'L (Skill 5)', description: 'Membaca 14 kata rahasia selama 4.5s. Jika lolos tanpa interupsi, berevolusi jadi C-Moon!' },
    ],
  },
  cmoon: {
    standName: 'C-Moon',
    title: 'Gravitational Axis Shift & Surface Inversion',
    skillsList: [
      { id: 'gravity_shift', name: 'Dynamic Gravity Axis Shift', command: 'U (Skill 1)', description: 'Mengubah sumbu gravitasi arena (Kanan -> Atas -> Kiri -> Bawah) membuat lawan dan proyektil jatuh ke arah baru!' },
      { id: 'inversion_punch', name: 'Surface Inversion Punch', command: 'I (Skill 2)', description: 'Pukulan membalikkan organ tubuh lawan dari dalam ke luar (mengabaikan defense / True Damage).' },
      { id: 'debris_launch', name: 'Debris Gravitational Launch', command: 'O (Skill 3)', description: 'Mengangkat puing-puing batu dari tanah menggunakan gravitasi dan melemparkannya sekaligus.' },
      { id: 'gravity_shield', name: 'Gravity Repel Shield', command: 'P (Skill 4)', description: 'Membuat perisai anti-gravitasi selama 2 detik yang memantulkan proyektil dan mendorong musuh.' },
      { id: 'cmoon_evolve', name: 'Cape Canaveral: Evolve to MiH', command: 'L (Evolve)', description: 'Saat Cape Canaveral Bar mencapai 100%, aktifkan untuk berevolusi menjadi Made in Heaven!' },
    ],
  },
  made_in_heaven: {
    standName: 'Made in Heaven',
    title: 'Infinite Velocity Acceleration & Universe Reset',
    skillsList: [
      { id: 'speed_blitz', name: 'Speed Blitz', command: 'U (Skill 1)', description: 'Meluncur melintasi layar dalam hitungan milidetik menebas musuh dari berbagai arah (Multi-Hit).' },
      { id: 'time_acceleration', name: 'Time Acceleration', command: 'I (Skill 2)', description: 'Mempercepat waktu secara ekstrem: Cooldown 0 detik selama 4 detik & lawan gerak super lambat!' },
      { id: 'invisible_knife', name: 'Invisible Knife Throw', command: 'O (Skill 3)', description: 'Melemparkan 5 pisau berkecepatan hipersonik yang tak terlihat musuh sampai menghantam tubuh.' },
      { id: 'teleport_strike', name: 'Speed Teleport Strike', command: 'P (Skill 4)', description: 'Teleportasi instan ke belakang musuh terdekat dan mendaratkan pukulan kritikal berkecepatan tinggi.' },
      { id: 'universe_reset', name: 'UNIVERSE RESET (Ultimate)', command: 'Y / L (Ultimate)', description: 'Memutar waktu alam semesta secara masif! Glitch layar putih total dan memicu ledakan AoE pemusnah massal.' },
    ],
  },
};

export const NPC_CHARACTERS: CharacterDef[] = [
  {
    id: 'vampire',
    name: 'Vampire Zombie',
    userName: 'Vampire Minion',
    standName: undefined,
    title: 'Blood Sucking Vampire Swarm (No Stand)',
    bodyColor: '#450a0a',
    standColor: '#7f1d1d',
    auraColor: 'crimson',
    eyeColor: '#ef4444',
    barrageCry: 'WRYYYYY!!',
    specialMove: 'Vampiric Drain Bite & Eye Laser',
    stats: {
      power: 'B',
      speed: 'A',
      range: 'B',
      durability: 'B',
    },
    skillsList: [
      { id: 'vampire_claw', name: 'Blood Claw Strike', command: 'J (Heavy)', description: 'Sabetan cakar tajam vampir berdarah.' },
      { id: 'vampire_frenzy', name: 'Claw Frenzy Rush', command: 'K (Barrage)', description: 'Rentetan sabetan cakar gila beruntun.' },
      { id: 'vampire_drain', name: 'Vampiric Drain Bite', command: 'U (Skill 1)', description: 'Menggigit dan menyedot darah musuh untuk menyembuhkan HP vampir (+40 HP).' },
      { id: 'space_ripper_small', name: 'Space Ripper Eye Beam', command: 'I (Skill 2)', description: 'Tembakan laser murni dari mata vampir.' },
    ],
    description: 'Pasukan vampir haus darah tanpa Stand yang bertarung buas, menyedot darah lawan, dan menyerang secara bergelombang.',
  },
];

export const ALL_CHARACTERS: CharacterDef[] = [...CHARACTERS, ...BOSS_CHARACTERS, ...NPC_CHARACTERS];

export function findCharacterById(id: string): CharacterDef | undefined {
  return ALL_CHARACTERS.find((c) => c.id === id);
}
